export enum Role {
    ADMIN = "ROLE_ADMIN",
    WARDEN = "ROLE_WARDEN",
    MANAGER = "ROLE_HUMAN_RESOURCES_MANAGER",
    EXECUTIONER = "ROLE_EXECUTIONER",
    SOCIAL = "ROLE_SOCIAL",
    MEDICAL = "ROLE_MEDICAL",
    GUARD = "ROLE_PRISON_GUARD",
    USER = "ROLE_USER"
}
